[project]
name = 'Identity-and-Access-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.access-control]
path = 'contracts/access-control.clar'
clarity_version = 2
epoch = 2.5

[contracts.device-identity]
path = 'contracts/device-identity.clar'
clarity_version = 2
epoch = 2.5

[contracts.firmware-updates]
path = 'contracts/firmware-updates.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
